# Introduction {#sec:introduction}

```{r definePrince5Location}
p5lon <- -66.850
p5lat <- 44.930
```

The Atlantic Zone Monitoring Program (AZMP) was proposed in year 1998 [@therriault1998]. The AZMP identified six fixed stations that was suggested to be sampled bi-weekly from February to October and monthly from November to January to collect biological, chemical, and physical oceanographic samples to resolve dynamics at a finer time-scale than the seasonal section sampling across the Atlantic regions: Newfoundland and Labrador, Quebec, Gulf, and Maritimes. For the Maritimes region, two fixed stations were proposed, Station 2 and Prince 5. Prince 5 is located at `r sprintf('%.4f', p5lat)`$^\circ$N, `r sprintf('%.4f', abs(p5lon))`$^\circ$W which is outside of Passamaquoddy Bay, New Brunswick, Canada in the Bay of Fundy at a depth of approximately 90 meters (m) (Figure \@ref(fig:map)). Monthly samples of temperature and salinity through the water column have been taken at Prince 5 since year 1921, and with sporadic biological sampling [@page2000pabm]. When the station became part of the AZMP, consistent biological and chemical sampling was added to align with the monitoring efforts across the Atlantic region. 

For monitoring efforts, the World Meteorological Organization (WMO) recommends using reference period of years 1961 to 1990 as well as the most recent three decades [@wmo2017]. While consistent monthly sampling of Prince 5 has occurred since year 1921, to align with other climatology calculations within the AZMP, only the two most recent overlapping three-decade periods, years 1981 to 2010 and years 1991 to 2020 will be calculated as well as the differences between the two. When differences are presented, they are the 1991 to 2020 value minus the 1981 to 2010 value.

Every year, conditions at Prince 5 are reported for the Maritimes region (e.g. @layton2024res) and the Atlantic Zone (e.g. @galbraith2025zonal). Conditions are compared by anomalies, which are deviations from the climatology reference period mean, or by normalized anomalies, the anomaly divided by the climatology reference period standard deviation (SD). The use of normalized anomalies and the same reference period allow for direct comparison among site variables. The anomalies on a monthly timescale for Prince 5 are used to calculate an annual composite to summarize long-term conditions. To support these calculations, the climatology for relevant variables is required. Hydrographic conditions, which include the variables temperature, salinity, and density, as a function of depth and time on daily and monthly timescales are reported for Prince 5 and a number of indicators on a monthly timescale. Indicators include near-surface temperature, near-surface salinity, stratification, and mixed layer depth.  The calculation methodology for each variable will be described and the resulting climatology mean and SD for both recent three-decade reference periods are calculated. 
