---
title: |
  "Maritimes Region Atlantic Zone Monitoring Program Prince 5 Hydrographic and Indicators 1991 to 2020 Climatology"
french_title: |
  "Prince 5 du Programme de monitorage de la zone Atlantique de la région des Maritimes – Données hydrographiques et indicateurs, climatologie de 1991 à 2020"
year: 2026
report_number: 233
author: |
  Chantelle Layton^1^
author_list: "Layton, C."
region: Maritimes Region
french_region: Région du Maritimes
isbn: "978-0-662-41244-1"
report_DOI: "10.60825/w574-h020" # do not include https://doi.org/
address: |
  ^1^Fisheries and Oceans Canada\
     Bedford Institute of Oceanography\
     P.O. Box 1006, 1 Challenger Drive\
     Dartmouth, Nova Scotia, B2Y 4A2\
french_address: |
  ^1^Pêches et Océans Canada\
     Division des sciences de l’océan et des écosystèmes\
     Institut océanographique de Bedford\
     Case postale 1006, 1, promenade Challenger\
     Dartmouth (Nouvelle-Écosse) B2Y 4A2\
phone: "(555) 555-5555"
author_footnote: "Email: First.Author@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  The Atlantic Zone Monitoring Program began in year 1998. It proposed six fixed stations across the Atlantic zone to be sampled every two weeks to resolve dynamics at a finer timescale than the seasonal regional scale surveys. Two stations were included in the Maritimes region, one of them being Prince 5, which is located outside of Passamaquoddy Bay, New Brunswick, Canada in the Bay of Fundy. The depth binned daily and monthly temperature, salinity, and density as well as daily and monthly indicators of near-surface temperature, near-surface salinity, stratification, and mixed layer depths for the 1991 to 2020 climatology reference period are calculated to support annual reporting on variability. Details on data acquisition and coverage are also provided.
french_abstract: |
  Le Programme de monitorage de la zone Atlantique a débuté en 1998. Il proposait six stations fixes réparties dans la zone Atlantique, échantillonnées toutes les deux semaines, afin de caractériser la dynamique à des échelles temporelles plus fines que celles couvertes par les relevés saisonniers régionaux. Deux stations ont été incluses dans la région des Maritimes, l’une d’entre elles est Prince 5, située à l’extérieur de la baie de Passamaquoddy, au Nouveau-Brunswick, au Canada, dans la baie de Fundy. Les températures, salinités et densités quotidiennes et mensuelles regroupées par tranches de profondeur, ainsi que les indicateurs quotidiens et mensuels de la température près de la surface, de la salinité près de la surface, de la stratification et de la profondeur de la couche de mélange, pour la période de référence climatologique 1991–2020, sont calculés afin d’appuyer les rapports annuels sur la variabilité. Des détails sur l’acquisition et la couverture des données sont également fournis.
# `show_continued_text` is a logical which, if `true`, places
# "Continued on the next page..." and "...Continued from the previous page" or
# the french equivalents (if `french` = `true`) on all long tables created
# with `csas_table()` that cross page boundaries. If `false`, these will
# both be absent from all tables. If it is missing or any other value than
# `false`, it will be assumed to be `true`
citation_french: "Last, F.M. et Smith, A.B. 2022. Titre ici (Nom d'espèce latin). Rapp. tech. can. sci. halieut. aquat. nnn : v + 18 p. https://doi.org/##.####/xxxxx"
show_continued_text: true
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: false
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) csasdown::render())
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(csasdown)
library(oce)
```
